### ISSUE TITLE
Prepare NixOS VMs for testing hybrid and unified cgroup hierarchies

### ISSUE THREAD

**Issue by wentasah** [CTU-IIG/demos-sched#55]

**Comment by MatejKafka** [comment]
Could you also add the Nix environment to the Github Actions tests we have, and run the test suite under it with the unified hierarchy?

**Comment by wentasah** [comment]
I've [added that](https://github.com/CTU-IIG/demos-sched/runs/2961208327?check_suite_focus=true), but some tests fail there even with cgroup v1. The problem is that these tests are time-dependent and when these are run under NixOS VM running under Github Actions VM/container, it's just too slow. But if your OS cannot run NixOS VMs ;-) GA should be usable (but unnecessarily slow) for initial development/testing.
