### ISSUE TITLE
DEmOS fails to execute long config file.

### ISSUE THREAD

**Issue by benedond** [CTU-IIG/demos-sched#69]
When trying to execute the attached config file [conf_600000.txt](https://github.com/CTU-IIG/demos-sched/files/7574633/conf_600000.txt), DEmOS fails with the following error:

```
>>> 13:24:01.625 [error] Exception: CgroupUnified::CgroupUnified(const string&, const string&): open((path + "/cgroup.events").c_str(), O_RDONLY | O_NONBLOCK): errno `24` - `Too many open files`: Too many open files
```

I hope that the config is syntactically correct, but maybe there are just too many partitions. Is there some limit?

**Comment by wentasah** [comment]
It seems that increasing the maximum number of open files helps:
```sh
ulimit -n 2000
demos-sched ...
```

**Comment by MatejKafka** [comment]
DEmOS keeps multiple file descriptors open for each scheduler object (iirc, 4 for each scheduled process, 1 for each partition and 1 for each slice). Linux has a default limit on the number of open file descriptors for each process, and refuses to open more. `ulimit` raises the FD limit to the provided value, which should resolve the issue.
